Traceback (most recent call last):
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\index.py", line 15, in <module>
    runMultiAccount()
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\main_multi_account.py", line 113, in runMultiAccount
    Action.refreshHeroesPositions()
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 103, in refreshHeroesPositions
    clickBtn(env.images['treasure-hunt-icon'])
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 34, in clickBtn
    matches = getPositions(img, threshold=threshold)
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 69, in getPositions
    img = printScreenForWindow(env.window_object, env.in_login_process == False)
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\utils\image.py", line 24, in printScreenForWindow
    window.activate()
[2022-02-18 22:35:06] ERROR:   File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pygetwindowmp\_pygetwindow_win.py", line 181, in activate
    win32gui.SetForegroundWindow(self._hWnd)
[2022-02-18 22:35:06] ERROR: pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')

Traceback (most recent call last):
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\index.py", line 15, in <module>
    runMultiAccount()
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\main_multi_account.py", line 103, in runMultiAccount
    Heroes.refreshHeroes()
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\heroes.py", line 140, in refreshHeroes
    goToHeroes()
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 91, in goToHeroes
    clickBtn(env.images['hero-icon'])
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 34, in clickBtn
    matches = getPositions(img, threshold=threshold)
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\bot\action.py", line 69, in getPositions
    img = printScreenForWindow(env.window_object, env.in_login_process == False)
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\Downloads\Bot Bomb\bot\src\utils\image.py", line 24, in printScreenForWindow
    window.activate()
[2022-02-18 22:35:56] ERROR:   File "C:\Users\Paulo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pygetwindowmp\_pygetwindow_win.py", line 181, in activate
    win32gui.SetForegroundWindow(self._hWnd)
[2022-02-18 22:35:56] ERROR: pywintypes.error: (0, 'SetForegroundWindow', 'No error message is available')

